// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// execute_time_loop_rcpp
Rcpp::List execute_time_loop_rcpp(double total_time, std::vector<double>& pars, Rcpp::List hyper_pars, Rcpp::List area_pars, int seed, int mainland_n, int island_ontogeny, int sea_level);
RcppExport SEXP _DAISIEiwsim_execute_time_loop_rcpp(SEXP total_timeSEXP, SEXP parsSEXP, SEXP hyper_parsSEXP, SEXP area_parsSEXP, SEXP seedSEXP, SEXP mainland_nSEXP, SEXP island_ontogenySEXP, SEXP sea_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type total_time(total_timeSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type hyper_pars(hyper_parsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type area_pars(area_parsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type mainland_n(mainland_nSEXP);
    Rcpp::traits::input_parameter< int >::type island_ontogeny(island_ontogenySEXP);
    Rcpp::traits::input_parameter< int >::type sea_level(sea_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(execute_time_loop_rcpp(total_time, pars, hyper_pars, area_pars, seed, mainland_n, island_ontogeny, sea_level));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DAISIEiwsim_execute_time_loop_rcpp", (DL_FUNC) &_DAISIEiwsim_execute_time_loop_rcpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_DAISIEiwsim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
