# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

execute_time_loop_rcpp <- function(total_time, pars, hyper_pars, area_pars, seed, mainland_n, island_ontogeny, sea_level) {
    .Call('_DAISIEiwsim_execute_time_loop_rcpp', PACKAGE = 'DAISIEiwsim', total_time, pars, hyper_pars, area_pars, seed, mainland_n, island_ontogeny, sea_level)
}

